// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppBarSearch: typeof import('./src/@core/components/AppBarSearch.vue')['default']
    AppDateTimePicker: typeof import('./src/@core/components/AppDateTimePicker.vue')['default']
    AppSearchHeader: typeof import('./src/@core/components/AppSearchHeader.vue')['default']
    CardStatisticsHorizontal: typeof import('./src/@core/components/CardStatisticsHorizontal.vue')['default']
    CardStatisticsVertical: typeof import('./src/@core/components/CardStatisticsVertical.vue')['default']
    CardStatisticsWithImages: typeof import('./src/@core/components/CardStatisticsWithImages.vue')['default']
    ConfirmDialog: typeof import('./src/@core/components/ConfirmDialog.vue')['default']
    EditAddressDialog: typeof import('./src/@core/components/EditAddressDialog.vue')['default']
    ErrorHeader: typeof import('./src/@core/components/ErrorHeader.vue')['default']
    I18n: typeof import('./src/@core/components/I18n.vue')['default']
    Notifications: typeof import('./src/@core/components/Notifications.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Shortcuts: typeof import('./src/@core/components/Shortcuts.vue')['default']
    ThemeSwitcher: typeof import('./src/@core/components/ThemeSwitcher.vue')['default']
    UserInfoEditDialog: typeof import('./src/@core/components/UserInfoEditDialog.vue')['default']
  }
}
